"""Repo/instance adapter generation for SWE-bench evaluator integration (bead q5b).

Generates two artifacts in the output directory:
  specs.json    -- serialised environment spec consumed by the eval runtime
  adapter.py    -- a tiny Python module that registers the repo with the harness

Both are produced deterministically from the repo profile produced by `mine`.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict


# ---------------------------------------------------------------------------
# Spec serialisation
# ---------------------------------------------------------------------------


def _safe_module_name(repo: str) -> str:
    """Turn ``owner/repo`` into a valid Python identifier ``owner__repo``."""
    sanitized = re.sub(r"[^a-zA-Z0-9_]", "_", repo or "")
    if not sanitized:
        return "_repogauge_repo"
    if not re.match(r"[A-Za-z_]", sanitized):
        sanitized = f"_{sanitized}"
    return sanitized


def build_adapter_spec(
    repo_name: str, environment_plan: Dict[str, Any]
) -> Dict[str, Any]:
    """Build a serialisable adapter spec dict from a repo name and env plan."""
    python_version = environment_plan.get("python_version", "3.11")
    pre_install = environment_plan.get("pre_install", [])
    install = environment_plan.get("install", ["pip install -e ."])
    build = environment_plan.get("build", [])
    test_cmd_base = environment_plan.get("test_cmd_base", "python -m pytest")
    strategy_name = environment_plan.get("strategy_name", "")

    return {
        "repo": repo_name,
        "version": str(environment_plan.get("version", "0.0.0")),
        "python_version": python_version,
        "pre_install": pre_install,
        "install": install,
        "build": build,
        "test_cmd_base": test_cmd_base,
        "strategy_name": strategy_name,
        "parser": "junit",
        "docker_specs": {"python_version": python_version},
        "module_name": _safe_module_name(repo_name),
    }


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------


_ADAPTER_TEMPLATE = '''\
# AUTO-GENERATED by repogauge -- do not edit by hand.
# Re-generate with: repogauge export ...
"""Harness registration adapter for {repo}."""

from __future__ import annotations

from repogauge.parsers.junit import parse_repogauge_junit

REPO = {repo_repr}
VERSION = {version_repr}
MODULE_NAME = {module_name_repr}
PYTHON_VERSION = {python_version_repr}
PRE_INSTALL = {pre_install_repr}
INSTALL = {install_repr}
BUILD = {build_repr}
TEST_CMD_BASE = {test_cmd_base_repr}
PARSER = "junit"
STRATEGY_NAME = {strategy_name_repr}
DOCKER_SPECS = {docker_specs_repr}

MAP_REPO_TO_EXT = {map_repo_to_ext_repr}
MAP_REPO_VERSION_TO_SPECS = {map_repo_version_specs_repr}
MAP_REPO_TO_PARSER = {map_repo_to_parser_repr}


def get_spec() -> dict:
    """Return the environment spec dict for this repo."""
    return {{
        "repo": REPO,
        "version": VERSION,
        "module_name": MODULE_NAME,
        "python_version": PYTHON_VERSION,
        "pre_install": PRE_INSTALL,
        "install": INSTALL,
        "build": BUILD,
        "test_cmd_base": TEST_CMD_BASE,
        "parser": PARSER,
        "strategy_name": STRATEGY_NAME,
        "docker_specs": DOCKER_SPECS,
    }}


def registration_context() -> dict:
    """Return the harness registration payload this adapter contributes."""
    return {{
        "repo": REPO,
        "version": VERSION,
        "module_name": MODULE_NAME,
        "maps": {{
            "repo_to_ext": MAP_REPO_TO_EXT,
            "repo_version_to_specs": MAP_REPO_VERSION_TO_SPECS,
            "repo_to_parser": MAP_REPO_TO_PARSER,
        }},
    }}
'''


def _render_adapter(spec: Dict[str, Any]) -> str:
    map_repo = repr(spec["repo"])
    map_repo_to_parser = f"{{{map_repo}: parse_repogauge_junit}}"
    return _ADAPTER_TEMPLATE.format(
        repo=spec["repo"],
        repo_repr=repr(spec["repo"]),
        version_repr=repr(spec["version"]),
        module_name_repr=repr(spec["module_name"]),
        python_version_repr=repr(spec["python_version"]),
        pre_install_repr=repr(spec["pre_install"]),
        install_repr=repr(spec["install"]),
        build_repr=repr(spec["build"]),
        test_cmd_base_repr=repr(spec["test_cmd_base"]),
        strategy_name_repr=repr(spec["strategy_name"]),
        docker_specs_repr=repr(spec["docker_specs"]),
        map_repo_to_ext_repr=repr({spec["repo"]: "py"}),
        map_repo_version_specs_repr=repr(
            {
                spec["repo"]: {
                    spec["version"]: {
                        "docker_specs": {"python_version": spec["python_version"]},
                        "pre_install": spec["pre_install"],
                        "install": spec["install"],
                        "build": spec["build"],
                        "test_cmd_base": spec["test_cmd_base"],
                        "parser": spec["parser"],
                        "strategy_name": spec["strategy_name"],
                    }
                }
            }
        ),
        map_repo_to_parser_repr=map_repo_to_parser,
    )


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def generate_adapter(
    repo_name: str,
    environment_plan: Dict[str, Any],
    *,
    out_root: Path,
) -> Dict[str, str]:
    """Write ``specs.json`` and ``adapter.py`` under *out_root*.

    Returns a dict with keys ``specs_path`` and ``adapter_path``.
    """
    out_root.mkdir(parents=True, exist_ok=True)
    spec = build_adapter_spec(repo_name, environment_plan)

    specs_path = out_root / "specs.json"
    specs_path.write_text(
        json.dumps(spec, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    adapter_path = out_root / f"adapter_{spec['module_name']}.py"
    adapter_path.write_text(_render_adapter(spec), encoding="utf-8")

    return {
        "specs_path": str(specs_path),
        "adapter_path": str(adapter_path),
        "repo": repo_name,
    }
