"""Repo/instance adapter generation for SWE-bench evaluator integration (bead q5b).

Generates two artifacts in the output directory:
  specs.json    -- serialised environment spec consumed by the eval runtime
  adapter.py    -- a tiny Python module that registers the repo with the harness

Both are produced deterministically from the repo_profile produced by `mine`.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict


# ---------------------------------------------------------------------------
# Spec serialisation
# ---------------------------------------------------------------------------


def _safe_module_name(repo: str) -> str:
    """Turn ``owner/repo`` into a valid Python identifier ``owner__repo``."""
    return re.sub(r"[^a-zA-Z0-9]", "_", repo)


def build_adapter_spec(
    repo_name: str, environment_plan: Dict[str, Any]
) -> Dict[str, Any]:
    """Build a serialisable adapter spec dict from a repo name and env plan."""
    return {
        "repo": repo_name,
        "python_version": environment_plan.get("python_version", "3.11"),
        "pre_install": environment_plan.get("pre_install", []),
        "install": environment_plan.get("install", ["pip install -e ."]),
        "build": environment_plan.get("build", []),
        "test_cmd_base": environment_plan.get("test_cmd_base", "python -m pytest"),
        "strategy_name": environment_plan.get("strategy_name", ""),
        "parser": "junit",
    }


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

_ADAPTER_TEMPLATE = '''\
# AUTO-GENERATED by repogauge — do not edit by hand.
# Re-generate with: repogauge export ...
"""Harness registration adapter for {repo}."""

from __future__ import annotations

REPO = {repo_repr}
PYTHON_VERSION = {python_version_repr}
PRE_INSTALL = {pre_install_repr}
INSTALL = {install_repr}
BUILD = {build_repr}
TEST_CMD_BASE = {test_cmd_base_repr}
PARSER = "junit"
STRATEGY_NAME = {strategy_name_repr}


def get_spec() -> dict:
    """Return the environment spec dict for this repo."""
    return {{
        "repo": REPO,
        "python_version": PYTHON_VERSION,
        "pre_install": PRE_INSTALL,
        "install": INSTALL,
        "build": BUILD,
        "test_cmd_base": TEST_CMD_BASE,
        "parser": PARSER,
        "strategy_name": STRATEGY_NAME,
    }}
'''


def _render_adapter(spec: Dict[str, Any]) -> str:
    return _ADAPTER_TEMPLATE.format(
        repo=spec["repo"],
        repo_repr=repr(spec["repo"]),
        python_version_repr=repr(spec["python_version"]),
        pre_install_repr=repr(spec["pre_install"]),
        install_repr=repr(spec["install"]),
        build_repr=repr(spec["build"]),
        test_cmd_base_repr=repr(spec["test_cmd_base"]),
        strategy_name_repr=repr(spec["strategy_name"]),
    )


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def generate_adapter(
    repo_name: str,
    environment_plan: Dict[str, Any],
    *,
    out_root: Path,
) -> Dict[str, str]:
    """Write ``specs.json`` and ``adapter.py`` under *out_root*.

    Returns a dict with keys ``specs_path`` and ``adapter_path``.
    """
    out_root.mkdir(parents=True, exist_ok=True)
    spec = build_adapter_spec(repo_name, environment_plan)

    specs_path = out_root / "specs.json"
    specs_path.write_text(
        json.dumps(spec, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    adapter_path = out_root / f"adapter_{_safe_module_name(repo_name)}.py"
    adapter_path.write_text(_render_adapter(spec), encoding="utf-8")

    return {
        "specs_path": str(specs_path),
        "adapter_path": str(adapter_path),
        "repo": repo_name,
    }
