"""Runner package."""

from .planner import (
    PlannedRunJob,
    RunManifest,
    plan_jobs,
    write_jobs,
    write_matrix_snapshot,
    write_run_manifest,
)
from .adapters import (
    SolverAdapterError,
    build_solver_adapters,
)
from .features import TASK_FEATURE_VERSION, TaskFeatureBundle, build_task_feature_bundle
from .router import (
    ROUTER_MODEL_VERSION,
    build_router_training_rows,
    evaluate_router_baselines,
    evaluate_router_model,
    load_router_training_rows,
    load_router_model,
    run_router_training,
    train_router_model,
    write_router_model,
    write_router_report,
    write_router_training_rows,
)
from .scheduler import (
    SolverAdapter,
    SolverAdapterRequest,
    SolverAdapterResult,
    SolverAttemptState,
    SolverScheduleResult,
    SolverScheduler,
    SolverSchedulerConfig,
    SolverSchedulerError,
)
from .solvers import (
    DEFAULT_SOLVER_ADAPTER_BY_PROVIDER,
    KNOWN_SOLVER_FIELDS,
    SOLVER_ADAPTER_ALIAS,
    SOLVER_ADAPTER_CLAUDE,
    SOLVER_ADAPTER_CODEX_CLI,
    SOLVER_ADAPTER_MOCK,
    SOLVER_ADAPTER_OPENAI_COMPATIBLE,
    SOLVER_ADAPTER_OPENCODE_CLI,
    SOLVER_ADAPTER_OPENAI_RESPONSES,
    SOLVER_ADAPTER_OPEN_CODEX_SERVER,
    SolverConfig,
    SolverConfigurationError,
    normalize_solver,
)

__all__ = [
    "PlannedRunJob",
    "RunManifest",
    "plan_jobs",
    "write_jobs",
    "write_matrix_snapshot",
    "write_run_manifest",
    "build_solver_adapters",
    "TASK_FEATURE_VERSION",
    "TaskFeatureBundle",
    "build_task_feature_bundle",
    "build_router_training_rows",
    "evaluate_router_baselines",
    "evaluate_router_model",
    "load_router_training_rows",
    "load_router_model",
    "run_router_training",
    "ROUTER_MODEL_VERSION",
    "train_router_model",
    "write_router_model",
    "write_router_report",
    "write_router_training_rows",
    "SolverAdapterError",
    "SolverAdapter",
    "SolverAdapterRequest",
    "SolverAdapterResult",
    "SolverAttemptState",
    "SolverScheduleResult",
    "SolverScheduler",
    "SolverSchedulerConfig",
    "SolverSchedulerError",
    "DEFAULT_SOLVER_ADAPTER_BY_PROVIDER",
    "KNOWN_SOLVER_FIELDS",
    "SOLVER_ADAPTER_ALIAS",
    "SOLVER_ADAPTER_CLAUDE",
    "SOLVER_ADAPTER_CODEX_CLI",
    "SOLVER_ADAPTER_MOCK",
    "SOLVER_ADAPTER_OPENAI_COMPATIBLE",
    "SOLVER_ADAPTER_OPENCODE_CLI",
    "SOLVER_ADAPTER_OPENAI_RESPONSES",
    "SOLVER_ADAPTER_OPEN_CODEX_SERVER",
    "SolverConfig",
    "SolverConfigurationError",
    "normalize_solver",
]
