# AUTO-GENERATED by repogauge -- do not edit by hand.
# Re-generate with: repogauge export ...
"""Harness registration adapter for s1liconcow/repogauge."""

from __future__ import annotations

from repogauge.parsers.junit import parse_repogauge_junit

REPO = 's1liconcow/repogauge'
VERSION = '0.0.0'
MODULE_NAME = 's1liconcow_repogauge'
LANGUAGE = 'python'
RUNTIME_VERSION = '3.10'
PYTHON_VERSION = '3.10'
PRE_INSTALL = []
INSTALL = ['uv sync --active --all-groups', 'python -m pip install pytest']
BUILD = []
TEST_CMD_BASE = 'python -m pytest'
PARSER = "junit"
STRATEGY_NAME = 'uv:pytest-default'
DOCKER_SPECS = {'python_version': '3.10'}

MAP_REPO_TO_EXT = {'s1liconcow/repogauge': 'py'}
MAP_REPO_VERSION_TO_SPECS = {'s1liconcow/repogauge': {'0.0.0': {'python': '3.10', 'python_version': '3.10', 'language': 'python', 'runtime_version': '3.10', 'pre_install': ['pip install uv'], 'install': 'uv sync --active --all-groups && python -m pip install pytest', 'test_cmd': 'python -m pytest', 'test_cmd_base': 'python -m pytest', 'build': [], 'parser': 'junit', 'strategy_name': 'uv:pytest-default', 'docker_specs': {'python_version': '3.10'}}}}
MAP_REPO_TO_PARSER = {REPO: parse_repogauge_junit}


def get_spec() -> dict:
    """Return the environment spec dict for this repo."""
    return {
        "repo": REPO,
        "version": VERSION,
        "module_name": MODULE_NAME,
        "language": LANGUAGE,
        "runtime_version": RUNTIME_VERSION,
        "python_version": PYTHON_VERSION,
        "pre_install": PRE_INSTALL,
        "install": INSTALL,
        "build": BUILD,
        "test_cmd_base": TEST_CMD_BASE,
        "parser": PARSER,
        "strategy_name": STRATEGY_NAME,
        "docker_specs": DOCKER_SPECS,
    }


def registration_context() -> dict:
    """Return the harness registration payload this adapter contributes."""
    return {
        "repo": REPO,
        "version": VERSION,
        "module_name": MODULE_NAME,
        "maps": {
            "repo_to_ext": MAP_REPO_TO_EXT,
            "repo_version_to_specs": MAP_REPO_VERSION_TO_SPECS,
            "repo_to_parser": MAP_REPO_TO_PARSER,
        },
    }
