"""CLI entrypoint for RepoGauge commands.

The current implementation intentionally focuses on scaffold shape. Commands resolve
flags and exit codes in a stable way so downstream modules can be built without
changing public invocation semantics.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path

from repogauge.export import run_export, run_materialization
from repogauge.review import run_review

from .logging_utils import log_event
from .manifest import Manifest, ManifestStepStatus
from .mining.inspect import inspect_repository
from .mining.scan import scan_repository

OUT_DIR_HELP = "Path where artifacts are written (created when needed)."
CONFIG_HELP = "Configuration file path. Values are merged over project defaults."
RESUME_HELP = "Resume into an existing artifact directory."
DRY_RUN_HELP = (
    "Validate inputs and render intended commands without mutating artifacts."
)
LLM_MODE_HELP = "Control model usage: off/local_only/allow_remote."
VERBOSE_HELP = "Enable verbose output."

COMMIT_RANGE_HELP = "Commit range to scan (for example HEAD~50..HEAD)."
MAX_COMMITS_HELP = "Maximum number of commits to inspect."
EXCLUDE_MERGES_HELP = "Skip merge commits during scanning."
ENRICH_GITHUB_HELP = "Add issue/PR metadata from GitHub API when refs are present."
GITHUB_TOKEN_HELP = "GitHub token for API calls (defaults to GITHUB_TOKEN env var)."
GITHUB_ENRICHMENT_CACHE_HELP = "Path for optional GitHub metadata cache (default: <out>/github_enrichment_cache.json)."


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="RepoGauge CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)

    for name in ["mine", "review", "export", "eval", "run", "analyze", "train-router"]:
        cmd = subparsers.add_parser(name, help=f"{name} command")
        cmd.add_argument("path", nargs="?", help="Command input path.")
        cmd.add_argument("--config", help=CONFIG_HELP)
        cmd.add_argument("--out", help=OUT_DIR_HELP)
        cmd.add_argument("--resume", action="store_true", help=RESUME_HELP)
        cmd.add_argument("--dry-run", action="store_true", help=DRY_RUN_HELP)
        cmd.add_argument(
            "--llm-mode",
            help=LLM_MODE_HELP,
            choices=["off", "local_only", "allow_remote"],
        )
        cmd.add_argument("--verbose", action="store_true", help=VERBOSE_HELP)
        if name == "review":
            cmd.add_argument(
                "--decisions",
                help="Optional JSON/JSONL file with scripted review decisions.",
            )
            cmd.add_argument(
                "--triage-hints",
                help="Optional structured JSON/JSONL file with advisory triage hints.",
            )
            cmd.add_argument(
                "--llm-model", help="Model identifier for advisory triage outputs."
            )
            cmd.add_argument("--llm-provider", help="LLM provider for advisory triage.")
        if name == "mine":
            cmd.add_argument("--commit-range", help=COMMIT_RANGE_HELP)
            cmd.add_argument(
                "--max-commits", default=100, type=int, help=MAX_COMMITS_HELP
            )
            cmd.add_argument(
                "--exclude-merges", action="store_true", help=EXCLUDE_MERGES_HELP
            )
            cmd.add_argument(
                "--enrich-github",
                action="store_true",
                help=ENRICH_GITHUB_HELP,
            )
            cmd.add_argument(
                "--github-token",
                help=GITHUB_TOKEN_HELP,
            )
            cmd.add_argument(
                "--github-enrichment-cache",
                help=GITHUB_ENRICHMENT_CACHE_HELP,
            )
        if name == "eval":
            cmd.add_argument(
                "--gold",
                action="store_true",
                help="Evaluate gold predictions (predictions.gold.jsonl).",
            )
            cmd.add_argument(
                "--predictions",
                help="Explicit predictions JSONL file (overrides --gold).",
            )
            cmd.add_argument(
                "--timeout",
                default=120,
                type=int,
                help="Per-instance pytest timeout in seconds.",
            )
            cmd.add_argument(
                "--adapter",
                help="Path to adapter_*.py generated by repogauge export. Auto-discovered when omitted.",
            )

    return parser


def _inputs_hash(command: str, namespace: argparse.Namespace) -> str:
    github_token = ""
    if command == "mine":
        if getattr(namespace, "github_token", None):
            github_token = namespace.github_token
        else:
            github_token = os.getenv("GITHUB_TOKEN", "")
    payload = {
        "command": command,
        "path": namespace.path or "",
        "config": namespace.config or "",
        "commit_range": namespace.commit_range if command == "mine" else "",
        "max_commits": namespace.max_commits if command == "mine" else 0,
        "exclude_merges": namespace.exclude_merges if command == "mine" else False,
        "enrich_github": namespace.enrich_github if command == "mine" else False,
        "github_token": github_token,
        "github_enrichment_cache_path": namespace.github_enrichment_cache
        if command == "mine"
        else "",
        "dry_run": bool(namespace.dry_run),
        "llm_mode": namespace.llm_mode or "",
        "llm_model": getattr(namespace, "llm_model", ""),
        "llm_provider": getattr(namespace, "llm_provider", ""),
        "triage_hints": getattr(namespace, "triage_hints", ""),
    }
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True).encode("utf-8")
    ).hexdigest()


def _resolve_eval_paths(source: Path) -> tuple[Path, Path]:
    """Return (dataset_path, gold_predictions_path) from a dataset path or directory."""
    if source.is_dir():
        dataset = source / "dataset" / "dataset.jsonl"
        predictions = source / "dataset" / "predictions.gold.jsonl"
    elif source.name == "dataset.jsonl":
        dataset = source
        predictions = source.parent / "predictions.gold.jsonl"
    else:
        dataset = source
        predictions = source.parent / "predictions.gold.jsonl"
    return dataset, predictions


def _resolve_repo_root(path_value: str | Path) -> Path:
    path = Path(path_value).resolve()
    if path.is_file():
        path = path.parent
    if (path / ".git").exists():
        return path
    try:
        from repogauge.utils.git import get_repo_root

        return Path(get_repo_root(path))
    except Exception:
        pass
    for ancestor in path.parents:
        if (ancestor / ".git").exists():
            return ancestor
    raise RuntimeError(f"cannot resolve repository root from {path_value}")


def _run_command(namespace: argparse.Namespace) -> int:
    command = namespace.command
    out_root = Path(namespace.out or Path(".") / ".repogauge" / command).resolve()
    out_root.mkdir(parents=True, exist_ok=True)

    manifest_path = out_root / "manifest.json"
    events_path = out_root / "events.jsonl"
    command_timestamp = (
        datetime.now(timezone.utc).replace(tzinfo=None).isoformat() + "Z"
    )

    if namespace.resume and manifest_path.exists():
        try:
            manifest = Manifest.load(manifest_path)
            if (
                manifest.inputs_hash == _inputs_hash(command, namespace)
                and manifest.status == "succeeded"
            ):
                manifest.mark_step(
                    "resume", ManifestStepStatus.SKIPPED, started_at=command_timestamp
                )
                manifest.finish(
                    status="succeeded",
                    metadata={"resume": True, "reason": "reused_existing_manifest"},
                )
                log_event(
                    {
                        "event": "command.resume",
                        "command": command,
                        "status": manifest.status,
                    },
                    events_path,
                )
                manifest.write(manifest_path)
                return 0
            manifest = Manifest.start(command)
        except Exception:
            manifest = Manifest.start(command)
    else:
        manifest = Manifest.start(command)

    manifest.inputs_hash = _inputs_hash(command, namespace)
    manifest.artifact_paths.update(
        {
            "manifest": str(manifest_path),
            "events": str(events_path),
        }
    )
    manifest.host_info = {
        "python_implementation": platform.python_implementation(),
        "platform": platform.platform(),
    }
    manifest.mark_step(
        "bootstrap", ManifestStepStatus.RUNNING, started_at=command_timestamp
    )
    manifest.write(manifest_path)
    log_event(
        {
            "event": "command.start",
            "command": command,
            "status": manifest.status,
            "path": namespace.path,
            "inputs_hash": manifest.inputs_hash,
            "timestamp": command_timestamp,
            "dry_run": bool(namespace.dry_run),
        },
        events_path,
    )

    if namespace.dry_run:
        manifest.mark_step("inspect", ManifestStepStatus.SKIPPED)
        manifest.mark_step("execute", ManifestStepStatus.SKIPPED)
        manifest.finish(status="succeeded", metadata={"reason": "dry_run"})
        manifest.mark_step("finish", ManifestStepStatus.SUCCEEDED)
        manifest.write(manifest_path)
        log_event(
            {
                "event": "command.finish",
                "command": command,
                "status": manifest.status,
                "timestamp": datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            },
            events_path,
        )
        return 0

    if command == "review":
        if not namespace.path:
            manifest.mark_step(
                "inspect",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.mark_step("execute", ManifestStepStatus.SKIPPED)
            manifest.finish(
                status="failed", metadata={"reason": "missing_review_input"}
            )
            manifest.mark_step(
                "finish",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                    "error": "missing review input path",
                },
                events_path,
            )
            return 1

        source = Path(namespace.path).resolve()
        candidates_path = source
        if source.is_dir():
            candidates_path = source / "candidates.jsonl"

        out_root = (
            Path(namespace.out or str(source.parent)).resolve()
            if source.is_file()
            else source.resolve()
        )
        manifest.mark_step(
            "inspect", ManifestStepStatus.RUNNING, started_at=command_timestamp
        )
        try:
            review_summary = run_review(
                candidates_path=candidates_path,
                out_root=out_root,
                decisions_path=Path(namespace.decisions).resolve()
                if namespace.decisions
                else None,
                llm_mode=namespace.llm_mode,
                triage_hints_path=Path(namespace.triage_hints).resolve()
                if namespace.triage_hints
                else None,
                llm_model_name=namespace.llm_model
                if hasattr(namespace, "llm_model")
                else None,
                llm_provider=namespace.llm_provider
                if hasattr(namespace, "llm_provider")
                else None,
            )
            for warning in review_summary.get("warnings", []):
                if warning:
                    print(f"warning: {warning}", file=sys.stderr)
            manifest.mark_step("inspect", ManifestStepStatus.SUCCEEDED)
            manifest.mark_step(
                "execute",
                ManifestStepStatus.SUCCEEDED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.artifact_paths["reviewed"] = review_summary["reviewed_path"]
            manifest.artifact_paths["review_markdown"] = review_summary["markdown_path"]
            manifest.artifact_paths["review_html"] = review_summary["html_path"]
            manifest.metadata["review"] = review_summary
        except Exception as exc:
            manifest.mark_step(
                "inspect",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.mark_step("execute", ManifestStepStatus.SKIPPED)
            manifest.finish(
                status="failed", metadata={"reason": "review_failed", "error": str(exc)}
            )
            manifest.mark_step(
                "finish",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                    "error": str(exc),
                },
                events_path,
            )
            return 1

        manifest.mark_step(
            "finish",
            ManifestStepStatus.SUCCEEDED,
            ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat() + "Z",
        )
        manifest.finish(
            status="succeeded",
            metadata={"reason": "review_complete", "path": namespace.path},
        )
        manifest.write(manifest_path)
        log_event(
            {
                "event": "command.finish",
                "command": command,
                "status": manifest.status,
                "timestamp": manifest.ended_at,
            },
            events_path,
        )
        return 0

    if command == "mine":
        manifest.mark_step(
            "inspect", ManifestStepStatus.RUNNING, started_at=command_timestamp
        )
        try:
            profile = inspect_repository(namespace.path or ".")
        except Exception as exc:  # pragma: no cover - defensive for unsupported paths
            manifest.mark_step(
                "inspect",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.mark_step("execute", ManifestStepStatus.SKIPPED)
            manifest.finish(
                status="failed",
                metadata={"reason": "inspect_failed", "error": str(exc)},
            )
            manifest.mark_step(
                "finish",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                    "error": str(exc),
                },
                events_path,
            )
            return 1

        repo_profile_path = out_root / "repo_profile.json"
        repo_profile_path.write_text(
            json.dumps(profile, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        manifest.artifact_paths["repo_profile"] = str(repo_profile_path)
        manifest.mark_step("inspect", ManifestStepStatus.SUCCEEDED)

        manifest.mark_step(
            "scan", ManifestStepStatus.RUNNING, started_at=command_timestamp
        )
        try:
            scan_rows = scan_repository(
                namespace.path or ".",
                repo_name=profile["repo_name"],
                max_count=int(namespace.max_commits),
                commit_range=namespace.commit_range,
                include_merges=not namespace.exclude_merges,
                enrich_github=bool(namespace.enrich_github),
                enrichment_cache_path=(
                    Path(namespace.github_enrichment_cache).expanduser()
                    if namespace.github_enrichment_cache
                    else out_root / "github_enrichment_cache.json"
                )
                if namespace.enrich_github
                else None,
                github_token=(
                    namespace.github_token
                    if namespace.github_token is not None
                    else os.getenv("GITHUB_TOKEN")
                ),
            )
        except Exception as exc:
            manifest.mark_step(
                "scan",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.mark_step("execute", ManifestStepStatus.SKIPPED)
            manifest.finish(
                status="failed", metadata={"reason": "scan_failed", "error": str(exc)}
            )
            manifest.mark_step(
                "finish",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                    "error": str(exc),
                },
                events_path,
            )
            return 1

        scan_path = out_root / "scan.jsonl"
        scan_path.write_text(
            "".join(
                json.dumps(row.to_dict(), sort_keys=True) + "\n" for row in scan_rows
            ),
            encoding="utf-8",
        )
        manifest.artifact_paths["scan"] = str(scan_path)

        candidates_path = out_root / "candidates.jsonl"
        candidates_path.write_text(
            "".join(
                json.dumps(row.to_dict(), sort_keys=True) + "\n" for row in scan_rows
            ),
            encoding="utf-8",
        )
        manifest.artifact_paths["candidates"] = str(candidates_path)
        manifest.mark_step(
            "scan",
            ManifestStepStatus.SUCCEEDED,
            ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat() + "Z",
        )
        manifest.metadata["scan"] = {
            "scan_count": len(scan_rows),
            "commit_range": namespace.commit_range,
            "max_commits": namespace.max_commits,
            "include_merges": not namespace.exclude_merges,
        }
        manifest.mark_step(
            "execute",
            ManifestStepStatus.SUCCEEDED,
            ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat() + "Z",
        )
        manifest.mark_step(
            "finish",
            ManifestStepStatus.SUCCEEDED,
            ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat() + "Z",
        )
        manifest.finish(
            status="succeeded",
            metadata={"reason": "scan_complete", "path": namespace.path},
        )
        manifest.write(manifest_path)
        log_event(
            {
                "event": "command.finish",
                "command": command,
                "status": manifest.status,
                "timestamp": manifest.ended_at,
            },
            events_path,
        )
        return 0

    if command == "export":
        if not namespace.path:
            manifest.mark_step(
                "inspect",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.mark_step("execute", ManifestStepStatus.SKIPPED)
            manifest.finish(
                status="failed", metadata={"reason": "missing_export_input"}
            )
            manifest.mark_step(
                "finish",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                    "error": "missing reviewed input path",
                },
                events_path,
            )
            return 1

        source = Path(namespace.path).resolve()
        reviewed_path = source / "reviewed.jsonl" if source.is_dir() else source
        if not reviewed_path.exists():
            manifest.mark_step(
                "inspect",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.mark_step("execute", ManifestStepStatus.SKIPPED)
            manifest.finish(
                status="failed",
                metadata={
                    "reason": "missing_reviewed_input",
                    "path": str(reviewed_path),
                },
            )
            manifest.mark_step(
                "finish",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                    "error": f"reviewed artifact not found: {reviewed_path}",
                },
                events_path,
            )
            return 1

        manifest.mark_step(
            "inspect", ManifestStepStatus.RUNNING, started_at=command_timestamp
        )
        try:
            repo_root = _resolve_repo_root(source)
            export_summary = run_materialization(
                reviewed_path=reviewed_path,
                out_root=out_root,
                repo_root=repo_root,
            )
            dataset_summary = run_export(
                materialized_path=export_summary["materialized_path"],
                out_root=out_root,
            )

            # Generate adapter spec so eval can load per-repo harness settings.
            from repogauge.export.adapter import generate_adapter

            adapter_repo_name = ""
            adapter_env_plan: dict = {}
            if export_summary.get("ready_count", 0) > 0:
                mat_path = Path(export_summary["materialized_path"])
                mat_rows = [
                    json.loads(ln)
                    for ln in mat_path.read_text(encoding="utf-8").splitlines()
                    if ln.strip()
                ]
                if mat_rows:
                    adapter_repo_name = mat_rows[0].get("repo", "")
            # Best-effort: look for environment_plan in sibling mine output.
            for profile_candidate in [
                source.parent / "mine" / "repo_profile.json",
                out_root.parent / "mine" / "repo_profile.json",
                source / "repo_profile.json",
            ]:
                if profile_candidate.exists():
                    try:
                        profile_data = json.loads(
                            profile_candidate.read_text(encoding="utf-8")
                        )
                        adapter_env_plan = profile_data.get("environment_plan", {})
                    except Exception:
                        pass
                    break
            if adapter_repo_name:
                adapter_result = generate_adapter(
                    adapter_repo_name, adapter_env_plan, out_root=out_root
                )
                manifest.artifact_paths["adapter"] = adapter_result["adapter_path"]
                manifest.artifact_paths["specs"] = adapter_result["specs_path"]

            manifest.mark_step("inspect", ManifestStepStatus.SUCCEEDED)
            manifest.artifact_paths["materialized"] = export_summary[
                "materialized_path"
            ]
            manifest.artifact_paths["materialization_rejections"] = export_summary[
                "rejected_path"
            ]
            manifest.artifact_paths["dataset"] = dataset_summary["dataset_path"]
            manifest.artifact_paths["predictions"] = dataset_summary["predictions_path"]
            manifest.metadata["export"] = {
                "ready_count": export_summary["ready_count"],
                "rejected_count": export_summary["rejected_count"],
                "total_count": export_summary["total_count"],
                "dataset_count": dataset_summary["dataset_count"],
                "prediction_count": dataset_summary["prediction_count"],
            }
            manifest.mark_step(
                "execute",
                ManifestStepStatus.SUCCEEDED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.mark_step(
                "finish",
                ManifestStepStatus.SUCCEEDED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.finish(
                status="succeeded",
                metadata={"reason": "export_complete", "path": namespace.path},
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                },
                events_path,
            )
            return 0
        except Exception as exc:
            manifest.mark_step(
                "inspect",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.mark_step("execute", ManifestStepStatus.SKIPPED)
            manifest.finish(
                status="failed", metadata={"reason": "export_failed", "error": str(exc)}
            )
            manifest.mark_step(
                "finish",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                    "error": str(exc),
                },
                events_path,
            )
            return 1

    if command == "eval":
        if not namespace.path:
            manifest.mark_step(
                "inspect",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.mark_step("execute", ManifestStepStatus.SKIPPED)
            manifest.finish(status="failed", metadata={"reason": "missing_eval_input"})
            manifest.mark_step(
                "finish",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                    "error": "missing dataset path",
                },
                events_path,
            )
            return 1

        source = Path(namespace.path).resolve()
        dataset_path, gold_predictions = _resolve_eval_paths(source)

        if namespace.predictions:
            predictions_path = Path(namespace.predictions).resolve()
        elif namespace.gold or True:  # default to gold when no explicit predictions
            predictions_path = gold_predictions

        if not dataset_path.exists():
            manifest.finish(
                status="failed",
                metadata={"reason": "dataset_not_found", "path": str(dataset_path)},
            )
            manifest.mark_step(
                "finish",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                    "error": f"dataset not found: {dataset_path}",
                },
                events_path,
            )
            return 1

        if not predictions_path.exists():
            manifest.finish(
                status="failed",
                metadata={
                    "reason": "predictions_not_found",
                    "path": str(predictions_path),
                },
            )
            manifest.mark_step(
                "finish",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                    "error": f"predictions not found: {predictions_path}",
                },
                events_path,
            )
            return 1

        manifest.mark_step(
            "inspect", ManifestStepStatus.RUNNING, started_at=command_timestamp
        )

        # --- Load adapter (per-repo harness settings) ----------------------------
        adapter_spec: dict | None = None
        adapter_path: Path | None = None
        if getattr(namespace, "adapter", None):
            adapter_path = Path(namespace.adapter).resolve()
            if not adapter_path.exists():
                manifest.finish(
                    status="failed",
                    metadata={"reason": "adapter_not_found", "path": str(adapter_path)},
                )
                manifest.mark_step(
                    "finish",
                    ManifestStepStatus.FAILED,
                    ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                    + "Z",
                )
                manifest.write(manifest_path)
                log_event(
                    {
                        "event": "command.finish",
                        "command": command,
                        "status": manifest.status,
                        "timestamp": manifest.ended_at,
                        "error": f"adapter not found: {adapter_path}",
                    },
                    events_path,
                )
                print(
                    f"repogauge eval: error: adapter not found: {adapter_path}",
                    file=sys.stderr,
                )
                print(
                    "repogauge eval: hint: run `repogauge export` first to generate the adapter",
                    file=sys.stderr,
                )
                return 1
        else:
            # Auto-discover adapter_*.py in the source directory.
            adapter_candidates = sorted(source.glob("adapter_*.py"))
            if adapter_candidates:
                adapter_path = adapter_candidates[0]

        if adapter_path is not None:
            try:
                import importlib.util as _ilu

                _mod_spec = _ilu.spec_from_file_location(
                    "_repogauge_adapter", adapter_path
                )
                _mod = _ilu.module_from_spec(_mod_spec)
                _mod_spec.loader.exec_module(_mod)
                adapter_spec = _mod.get_spec()
                print(f"repogauge eval: adapter={adapter_path}", file=sys.stderr)
                print(
                    f"repogauge eval: harness=local-pytest  "
                    f"repo={adapter_spec.get('repo')}  "
                    f"python={adapter_spec.get('python_version')}  "
                    f"test_cmd={adapter_spec.get('test_cmd_base')}",
                    file=sys.stderr,
                )
                specs_path = adapter_path.parent / "specs.json"
                if specs_path.exists():
                    print(f"repogauge eval: specs={specs_path}", file=sys.stderr)
            except Exception as exc:
                print(
                    f"repogauge eval: warning: could not load adapter {adapter_path}: {exc}",
                    file=sys.stderr,
                )
                print(
                    "repogauge eval: hint: re-run `repogauge export` to regenerate the adapter",
                    file=sys.stderr,
                )
        else:
            print(
                "repogauge eval: no adapter found; run `repogauge export` to generate one (using default harness settings)",
                file=sys.stderr,
            )

        print(f"repogauge eval: dataset={dataset_path}", file=sys.stderr)
        print(f"repogauge eval: predictions={predictions_path}", file=sys.stderr)
        print("repogauge eval: dispatching to local-pytest harness", file=sys.stderr)

        try:
            from repogauge.validation.validate import run_eval

            eval_summary = run_eval(
                dataset_path=dataset_path,
                predictions_path=predictions_path,
                out_root=out_root,
                timeout_seconds=getattr(namespace, "timeout", 120),
                adapter_spec=adapter_spec,
            )
            manifest.mark_step("inspect", ManifestStepStatus.SUCCEEDED)
            manifest.mark_step(
                "execute",
                ManifestStepStatus.SUCCEEDED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.artifact_paths["validation"] = eval_summary["validation_path"]
            manifest.metadata["eval"] = {
                k: v for k, v in eval_summary.items() if k != "validation_path"
            }
            manifest.mark_step(
                "finish",
                ManifestStepStatus.SUCCEEDED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.finish(status="succeeded", metadata={"reason": "eval_complete"})
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                },
                events_path,
            )
            total = eval_summary["total"]
            resolved = eval_summary["resolved"]
            rate = eval_summary["resolve_rate"]
            print(
                f"repogauge eval: {resolved}/{total} resolved ({rate:.1%})",
                file=sys.stderr,
            )
            return 0
        except Exception as exc:
            manifest.mark_step(
                "inspect",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.mark_step("execute", ManifestStepStatus.SKIPPED)
            manifest.finish(
                status="failed", metadata={"reason": "eval_failed", "error": str(exc)}
            )
            manifest.mark_step(
                "finish",
                ManifestStepStatus.FAILED,
                ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                + "Z",
            )
            manifest.write(manifest_path)
            log_event(
                {
                    "event": "command.finish",
                    "command": command,
                    "status": manifest.status,
                    "timestamp": manifest.ended_at,
                    "error": str(exc),
                },
                events_path,
            )
            return 1

    # Scaffold implementations are intentionally explicit no-ops for unimplemented commands.
    manifest.mark_step(
        "execute", ManifestStepStatus.SUCCEEDED, started_at=command_timestamp
    )
    manifest.mark_step(
        "finish",
        ManifestStepStatus.SUCCEEDED,
        ended_at=datetime.now(timezone.utc).replace(tzinfo=None).isoformat() + "Z",
    )
    manifest.finish(
        status="succeeded", metadata={"reason": "scaffolded", "path": namespace.path}
    )
    manifest.write(manifest_path)
    log_event(
        {
            "event": "command.finish",
            "command": command,
            "status": manifest.status,
            "timestamp": manifest.ended_at,
        },
        events_path,
    )

    return 0


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    if getattr(args, "command", None) is None:
        parser.print_help()
        return 2

    return _run_command(args)


if __name__ == "__main__":
    sys.exit(main())
